services:
  db:
    image: postgres:16
    restart: always
    container_name: drip-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: drip123
      POSTGRES_DB: dripdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
